# dongle
CONFIG_PROSPECTOR_FIXED_BRIGHTNESS=80
CONFIG_PROSPECTOR_USE_AMBIENT_LIGHT_SENSOR=n

# dongle backlight
CONFIG_LED_PWM=y

# how many peripherals can the central role connect to
CONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS=2
