# dongle
CONFIG_PROSPECTOR_FIXED_BRIGHTNESS=60
CONFIG_PROSPECTOR_USE_AMBIENT_LIGHT_SENSOR=n
CONFIG_PROSPECTOR_STATUS_SCREEN_OPERATOR=y

# dongle backlight
CONFIG_LED_PWM=y

# how many peripherals can the central role connect to
CONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS=2
